// import Head from "next/head";
// import Image from "next/image";
import { Reset } from "styled-reset";
import Link from "next/link";
import Main from "../components/Layout/Layout";
import Header from "../components/Layout/Header";
import UserCalendar from "../components/Calendar/Calendar";
import Button from "../components/UI/Button";

// 사용자 일기 데이터 불러와서 달력에 표시해줘야 함
const USER_POST = [
  {
    post_id: 1,
    user_id: 1,
    post_date: "2022-06-10",
    post_text: "오늘은 어쩌구저쩌구",
  },
  {
    post_id: 2,
    user_id: 1,
    post_date: "2022-06-11",
    post_text: "오늘은 어쩌구저쩌구",
  },
];

export default function Home() {
  return (
    <>
      <Reset />
      <UserCalendar userPost={USER_POST}/>
      {/* 각 날짜 클릭시 이동해야하지만 우선 버튼으로 대체 */}
      <Link href="/emotions"><Button>일기쓰기(임시)</Button></Link>
    </>
  );
}

{
  /* <Head>
<title>Dairy</title>
<meta name="description" content="Generated by create next app" />
<link rel="icon" href="/favicon.ico" />
</Head>
<Body> */
}
