// import Head from "next/head";
// import Image from "next/image";
import { Reset } from "styled-reset";
import Main from "../components/Layout/Layout";
import Header from "../components/Layout/Header";
import Calendar from "../components/Calendar/Calendar";

// 사용자 일기 데이터 불러와서 달력에 표시해줘야 함
const USER_POST = [
  {
    post_id: 1,
    user_id: 1,
    post_date: "2022-06-10",
    post_text: "오늘은 어쩌구저쩌구",
  },
  {
    post_id: 2,
    user_id: 1,
    post_date: "2022-06-11",
    post_text: "오늘은 어쩌구저쩌구",
  },
];

export default function Home() {
  return (
    <>
      <Reset />
      <Calendar userPost={USER_POST}/>
    </>
  );
}

{
  /* <Head>
<title>Dairy</title>
<meta name="description" content="Generated by create next app" />
<link rel="icon" href="/favicon.ico" />
</Head>
<Body> */
}
